services:
  - type: web
    name: pneumali-backend
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod,render
      - key: PORT
        value: 10000
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
        sync: false
      - key: JWT_EXPIRATION
        value: 86400000
      - key: JWT_REFRESH_EXPIRATION
        value: 604800000
      - key: APP_MAIL_PROVIDER
        value: sendgrid
      - key: SENDGRID_API_KEY
        sync: false
      - key: APP_MAIL_FROM
        value: amadoulandoure004@gmail.com
      - key: APP_CORS_ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /actuator/health
    autoDeploy: true

